fix(ascii2d): changed to ascii2d GET interface, fix #26
koishijs/koishi-plugin-image-search pull request #28
Opened 2024-04-10 12:15 UTC by Container-Zero

修改为 ascii2d 的 GET 接口，以节省请求资源，并规避高版本 koishi 下 Formdata 报错而无法使用 ascii2d 接口的错误。

2024-04-12 08:00 UTC, MaikoTan requested changes

2024-04-12 08:00 UTC, MaikoTan commented on src/ascii2d.ts
> +    });
```suggestion
    })
```

2024-04-15 01:40 UTC, MaikoTan reviewed
Looks good to me, could you change the koishi version in package.json to 4.17.0 or newer for forcing the new api for fetching resources?

2024-04-15 09:52 UTC, Container-Zero commented
> Looks good to me, could you change the koishi version in package.json to 4.17.0 or newer for forcing the new api for fetching resources?

Modified.

2024-04-15 21:46 UTC, shigma approved these changes

2024-04-16 18:08 UTC, merged